export const hours = [
  { hour: "09:00", isActive: false },
  { hour: "09:15", isActive: false },
  { hour: "09:30", isActive: false },
  { hour: "09:45", isActive: false },
  { hour: "10:00", isActive: false },
  { hour: "10:15", isActive: false },
  { hour: "10:30", isActive: false },
  { hour: "10:45", isActive: false },
  { hour: "11:00", isActive: false },
  { hour: "11:15", isActive: false },
  { hour: "11:30", isActive: false },
  { hour: "11:45", isActive: false },
  { hour: "12:00", isActive: false },
  { hour: "12:15", isActive: false },
  { hour: "12:30", isActive: false },
  { hour: "12:45", isActive: false },
  { hour: "13:00", isActive: false },
  { hour: "13:15", isActive: false },
  { hour: "13:30", isActive: false },
  { hour: "13:45", isActive: false },
  { hour: "14:00", isActive: false },
  { hour: "14:15", isActive: false },
  { hour: "14:30", isActive: false },
  { hour: "14:45", isActive: false },
  { hour: "15:00", isActive: false },
  { hour: "15:15", isActive: false },
  { hour: "15:30", isActive: false },
  { hour: "15:45", isActive: false },
  { hour: "16:00", isActive: false },
];
export const servicesDetails = [
  {
    name: "Manicure Klasyczny",
    isActive: false,
    duration: 90,
    price: "120PLN",
  },
  {
    name: "Manicure Hybrydowy",
    isActive: false,
    duration: 120,
    price: "120PLN",
  },
  {
    name: "Uzupełnienie żelowe",
    isActive: false,
    duration: 150,
    price: "120PLN",
  },
  {
    name: "Przedłużenie paznokci żelem",
    isActive: false,
    duration: 170,
    price: "120PLN",
  },
  { name: "Pedicure", isActive: false, duration: 60, price: "120PLN" },
];
