export const hours = [
  { value: "09:00", isActive: false },
  { value: "09:15", isActive: false },
  { value: "09:30", isActive: false },
  { value: "09:45", isActive: false },
  { value: "10:00", isActive: false },
  { value: "10:15", isActive: false },
  { value: "10:30", isActive: false },
  { value: "10:45", isActive: false },
  { value: "11:00", isActive: false },
  { value: "11:15", isActive: false },
  { value: "11:30", isActive: false },
  { value: "11:45", isActive: false },
  { value: "12:00", isActive: false },
  { value: "12:15", isActive: false },
  { value: "12:30", isActive: false },
  { value: "12:45", isActive: false },
  { value: "13:00", isActive: false },
  { value: "13:15", isActive: false },
  { value: "13:30", isActive: false },
  { value: "13:45", isActive: false },
  { value: "14:00", isActive: false },
  { value: "14:15", isActive: false },
  { value: "14:30", isActive: false },
  { value: "14:45", isActive: false },
  { value: "15:00", isActive: false },
  { value: "15:15", isActive: false },
  { value: "15:30", isActive: false },
  { value: "15:45", isActive: false },
  { value: "16:00", isActive: false },
  { value: "16:15", isActive: false },
  { value: "16:30", isActive: false },
  { value: "16:45", isActive: false },
  { value: "17:00", isActive: false },
  { value: "17:15", isActive: false },
  { value: "17:30", isActive: false },
  { value: "17:45", isActive: false },
  { value: "18:00", isActive: false },
  { value: "18:15", isActive: false },
  { value: "18:30", isActive: false },
  { value: "18:45", isActive: false },
  { value: "19:00", isActive: false },
  { value: "19:15", isActive: false },
  { value: "19:30", isActive: false },
  { value: "19:45", isActive: false },
  { value: "20:00", isActive: false },
  { value: "20:15", isActive: false },
  { value: "20:30", isActive: false },
  { value: "20:45", isActive: false },
  { value: "21:00", isActive: false },
];
export const salonWorkers = [
  { value: "Justyna", isActive: true },
  { value: "Monika", isActive: false },
];
export const servicesDetails = [
  {
    value: "Manicure Klasyczny",
    isActive: false,
    duration: 90,
    price: "40PLN",
  },
  {
    value: "Manicure Hybrydowy",
    isActive: false,
    duration: 120,
    price: "80PLN",
  },
  {
    value: "Uzupełnienie żelowe",
    isActive: false,
    duration: 150,
    price: "120PLN",
  },
  {
    value: "Przedłużenie paznokci żelem",
    isActive: false,
    duration: 180,
    price: "140PLN",
  },
  { value: "Pedicure", isActive: false, duration: 60, price: "120PLN" },
];

export const openingHours = [
  {
    fullName: "Niedziela",
    shortName: "Nd.",
    isActive: false,
    disabled: false,
    id: 0,
    hours: { start: "07:00", end: "16:00" },
  },
  {
    fullName: "Poniedziałek",
    shortName: "Pon.",
    isActive: true,
    disabled: false,
    id: 1,
    hours: { start: "07:00", end: "16:00" },
  },
  {
    fullName: "Wtorek",
    shortName: "Wt.",
    isActive: false,
    disabled: false,
    id: 2,
    hours: { start: "07:00", end: "16:00" },
  },
  {
    fullName: "Środa",
    shortName: "Śr.",
    isActive: false,
    disabled: false,
    id: 3,
    hours: { start: "07:00", end: "16:00" },
  },
  {
    fullName: "Czwartek",
    shortName: "Czw.",
    isActive: false,
    disabled: false,
    id: 4,
    hours: { start: "07:00", end: "16:00" },
  },
  {
    fullName: "Piątek",
    shortName: "Pt.",
    isActive: false,
    disabled: false,
    id: 5,
    hours: { start: "07:00", end: "16:00" },
  },
  {
    fullName: "Sobota",
    shortName: "Sb.",
    isActive: false,
    disabled: false,
    id: 6,
    hours: { start: "07:00", end: "16:00" },
  },
];
